spring:
  application:
    name: task-management
  datasource:
    url: jdbc:postgresql://localhost:5432/task_management
    username: task_management
    password: task_management
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
